name = "quicktax"
main = "src/index.js"
compatibility_date = "2025-01-01"

# Observability configuration
[observability]
enabled = true

[site]
bucket = "./dist"

[env.production]
route = "quicktax.nekopanlab.com/*"

# Build configuration
[build]
command = "npm run build"

# Upload rules
[[rules]]
type = "Text"
globs = ["**/*.html", "**/*.css", "**/*.js", "**/*.json", "**/*.webmanifest"]

[[rules]]
type = "Data"
globs = ["**/*.png", "**/*.svg", "**/*.ico", "**/*.jpg", "**/*.jpeg", "**/*.woff", "**/*.woff2"]