name = "quicktax"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2025-01-01"

# Observability configuration
[observability]
enabled = true

[site]
bucket = "./dist"
entry-point = "workers-site"

[build]
command = "npm run build && cd workers-site && npm install"

[env.production]
workers_dev = false
route = "quicktax.nekopanlab.com/*"